<?php

namespace FakerCryptoPHP\Provider\en_US;

use FakerCryptoPHP\AbstractCrypto;

class Crypto extends AbstractCrypto
{
  /**
   * @var string[] List of 3 digit crypto codes
   */
  protected static $codes = [
    'DPI', 'CFV', 'EGG', 'YMD', 'OSV', 'LNC', 'UDP', 'SWM', 'DAI', 'DSO',
    'AEH', 'EPV', 'CST', 'NJK', 'VEH', 'ZPW', 'RZT', 'BNI', 'KVG', 'LQR',
    'YHU', 'XLL', 'NDB', 'HNU', 'GKO', 'JXQ', 'FNB', 'NWD', 'XAQ', 'MUM',
    'KCY', 'UUE', 'OUK', 'GAQ', 'DVO', 'CBY', 'RYG', 'WZG', 'LVJ', 'UCB',
    'UDL', 'CPN', 'XQD', 'DPN', 'MSO', 'DEV', 'HWF', 'QZQ', 'OYH', 'APN',
    'CYF', 'PJA', 'RUP', 'BVE', 'EJE', 'UPD', 'BED', 'YVA', 'PPP', 'PFI',
    'CQV', 'EVM', 'TBP', 'FBV', 'WSO', 'DFM', 'GRI', 'YQF', 'VRR', 'VWO',
    'BVI', 'AEM', 'HZU', 'VTQ', 'TWE', 'FHI', 'BZD', 'TXM', 'ANQ', 'TXW',
    'NAC', 'MBQ', 'WLO', 'ICL', 'JOL', 'YYP', 'FJG', 'BZX', 'CXR', 'JFH',
    'GVR', 'AQK', 'TIB', 'MDF', 'BZU', 'CTF', 'ELS', 'BER', 'OYG', 'LCI'
  ];

  /**
  * @var string[] List of crypto coins names
  */
  protected static $cryptoCoinNames = [
    'AuroraX',
    'CryptoFusion',
    'Nexusphere',
    'ApexCoin',
    'Luminari',
    'QuantumBit',
    'Eonix',
    'Cryptra',
    'AxiomX',
    'PulseChain',
    'NovaSpire',
    'Cryptium',
    'Aetherium',
    'Kairos',
    'SpectraCoin',
    'ParagonX',
    'HelixCoin',
    'Cygnus',
    'Eclipse',
    'Lumina',
    'Cryptosphere',
    'Apexium',
    'NebulaX',
    'Cryptech',
    'Aurora',
    'Quantum',
    'Eon',
    'CryptraX',
    'Axiom',
    'Pulse',
    'Nova',
    'CryptiumX',
    'Aether',
    'KairosX',
    'Spectra',
    'Paragon',
    'Helix',
    'CygnusX',
    'EclipseX',
    'LuminaX',
    'CryptosphereX',
    'ApexiumX',
    'Nebula',
    'CryptechX',
    'AuroraX2',
    'CryptoFusionX',
    'NexusphereX',
    'ApexCoinX',
    'LuminariX',
    'QuantumBitX',
    'EonixX',
    'CryptraX2',
    'AxiomX2',
    'PulseChainX',
    'NovaSpireX',
    'CryptiumX2',
    'AetheriumX',
    'KairosX2',
    'SpectraCoinX',
    'ParagonX2',
    'HelixCoinX',
    'CygnusX2',
    'EclipseX2',
    'LuminaX2',
    'CryptosphereX2',
    'ApexiumX2',
    'NebulaX2',
    'CryptechX2',
    'AuroraX3',
    'CryptoFusionX2',
    'NexusphereX2',
    'ApexCoinX2',
    'LuminariX2',
    'QuantumBitX2',
    'EonixX2',
    'CryptraX3',
    'AxiomX3',
    'PulseChainX2',
    'NovaSpireX2',
    'CryptiumX3',
    'AetheriumX2',
    'KairosX3',
    'SpectraCoinX2',
    'ParagonX3',
    'HelixCoinX2',
    'CygnusX3',
    'EclipseX3',
    'LuminaX3',
    'CryptosphereX3',
    'ApexiumX3',
    'NebulaX3',
    'CryptechX3',
  ];
}