name: Workflow FakerCryptoPHP

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2 # Use v2 for stability

      - name: Cleanup
        run: |
          rm -rf ./vendor
          rm -rf ./src/Provider/en_us
          composer dump-autoload -o

      - name: Setting up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"

      - name: Running Composer Install
        run: |
          chmod +x ./.github/scripts/run-composer.sh
          ./.github/scripts/run-composer.sh

      - name: Running PHPStan
        run: |
          chmod +x ./.github/scripts/run-phpstan.sh
          ./.github/scripts/run-phpstan.sh

      - name: Check directory structure
        run: |
          ls -R ./src

      - name: Running PHPUnit
        run: |
          chmod +x ./.github/scripts/run-phpunit.sh
          ./.github/scripts/run-phpunit.sh
